version: '3'

services:

  database:
    container_name: database
    hostname: database
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DOCKER_POSTGRES_PASSWORD}
    networks:
      - mainnetwork

  migrate:
    container_name: migrate
    build:
      context: .
      dockerfile: ./packages/db/Dockerfile
    env_file:
      - .env
    networks:
      - mainnetwork
    depends_on:
      - database

  website:
    container_name: website
    hostname: website
    build:
      context: .
      dockerfile: ./apps/web-app/Dockerfile
    env_file:
      - .env
    networks:
      - mainnetwork
    # ports:
    #   - 3000:3000
    depends_on:
      - database
      - migrate

  stream:
    container_name: stream
    hostname: stream
    build:
      context: .
      dockerfile: ./apps/stream-app/Dockerfile
    env_file:
      - .env
    networks:
      - mainnetwork
    volumes:
      - type: bind
        source: /data
        target: /data
    # ports:
    #   - 6969:6969
    depends_on:
      - website

networks:
  mainnetwork:
    external: true
