version: '3'

services:

  database_dev:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DOCKER_POSTGRES_PASSWORD}

  studio_dev:
    build:
      context: .
      dockerfile: ./packages/db/Dockerfile
    env_file:
      - .env.dev
    depends_on:
      - database_dev

  website_dev:
    hostname: website_dev
    build:
      context: .
      dockerfile: ./apps/web-app/Dockerfile
    networks:
      - mainnetwork
    env_file:
      - .env.dev
    depends_on:
      - database_dev
      - studio_dev

  stream_dev:
    build:
      context: .
      dockerfile: ./apps/stream-app/Dockerfile
    env_file:
      - .env.dev
    depends_on:
      - website_dev

networks:
  mainnetwork:
    external: true
