version: '3'

services:

  database:
    container_name: database
    hostname: database
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DOCKER_POSTGRES_PASSWORD}

  studio:
    container_name: studio
    build:
      context: .
      dockerfile: ./packages/db/Dockerfile
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - database

  website:
    container_name: website
    hostname: website
    build:
      context: .
      dockerfile: ./apps/web-app/Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - database
      - studio

  stream:
    container_name: stream
    hostname: stream
    build:
      context: .
      dockerfile: ./apps/stream-app/Dockerfile
    env_file:
      - .env
    ports:
      - 6969:6969
    depends_on:
      - website
