version: '3'

services:
  stream:
    build:
      context: .
      dockerfile: ./apps/stream-app/Dockerfile
    env_file:
      - .env
    networks:
      - mainnetwork
    volumes:
      - type: bind
        source: ${DOCKER_STREAM_DATA}
        target: /data

networks:
  mainnetwork:
    external: true
