version: '3'

services:

  database:
    container_name: database
    hostname: database
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DOCKER_POSTGRES_PASSWORD}
    networks:
      - mainnetwork
    volumes:
      - type: bind
        source: ${DOCKER_POSTGRES_DATA}
        target: /var/lib/postgresql/data
    restart: on-failure

  studio:
    container_name: studio
    build:
      context: .
      dockerfile: ./packages/db/Dockerfile
    env_file:
      - .env
    networks:
      - mainnetwork
    depends_on:
      - database
    restart: on-failure

  website:
    container_name: website
    hostname: website
    build:
      context: .
      dockerfile: ./apps/web-app/Dockerfile
    env_file:
      - .env
    networks:
      - mainnetwork
    depends_on:
      - database
      - studio
    restart: on-failure

  stream:
    container_name: stream
    hostname: stream
    build:
      context: .
      dockerfile: ./apps/stream-app/Dockerfile
    env_file:
      - .env
    networks:
      - mainnetwork
    volumes:
      - type: bind
        source: ${DOCKER_STREAM_DATA}
        target: /data
    # depends_on:
    #   - website
    restart: on-failure

networks:
  mainnetwork:
    external: true
